import { retailPriceAud, formatAud } from "./lib/pricing.mjs";

const $prints = document.getElementById("prints");

async function loadJson(url, optional = false) {
    try {
        const res = await fetch(url, { cache: "no-cache" });
        if (!res.ok) throw new Error(`${url}: ${res.status}`);
        return await res.json();
    } catch (err) {
        if (optional) return null;
        throw err;
    }
}

const [config, frames, prints, stripeCfg] = await Promise.all([
    loadJson("config/store.config.json"),
    loadJson("config/frames.json"),
    loadJson("config/prints.json"),
    loadJson("config/stripe.json", true), // generated by scripts/stripe-setup.mjs
]);

const sizesById = Object.fromEntries(frames.sizes.map((s) => [s.id, s]));

// Rectangular sizes come in both orientations at the same price —
// show each print's sizes in its own orientation.
const sizeText = (size, orientation) =>
    orientation === "portrait" && size.shape !== "square"
        ? `${size.hCm} × ${size.wCm} cm`
        : `${size.wCm} × ${size.hCm} cm`;
const stripeReady = Boolean(stripeCfg?.products) || Boolean(config.checkoutEndpoint);

$prints.innerHTML = "";

if (!stripeReady) {
    const notice = document.createElement("p");
    notice.className = "notice";
    notice.textContent =
        "Checkout isn’t connected yet — run scripts/stripe-setup.mjs to generate Stripe payment links (see README).";
    $prints.appendChild(notice);
}

for (const print of prints.filter((p) => p.active)) {
    $prints.appendChild(renderCard(print));
}

function renderCard(print) {
    const card = document.createElement("article");
    card.className = "print-card";

    const state = {
        sizeId: print.sizes[0],
        colourId: frames.colours[0].id,
        matteId: frames.mattes?.[0]?.id ?? null,
    };

    const frameEl = document.createElement("div");
    frameEl.className = "frame";
    if (print.orientation && print.orientation !== "landscape") {
        frameEl.classList.add(print.orientation);
    }
    const inner = document.createElement("div");
    inner.className = "frame-inner";
    const img = document.createElement("img");
    img.src = print.image;
    img.alt = `${print.title} — framed print preview`;
    img.loading = "lazy";
    inner.appendChild(img);
    frameEl.appendChild(inner);

    const h2 = document.createElement("h2");
    h2.textContent = print.title;

    // Size select
    const sizeRow = document.createElement("div");
    sizeRow.className = "control-row";
    const sizeLabel = document.createElement("label");
    sizeLabel.textContent = "Size";
    sizeLabel.htmlFor = `size-${print.slug}`;
    const select = document.createElement("select");
    select.id = `size-${print.slug}`;
    for (const sizeId of print.sizes) {
        const size = sizesById[sizeId];
        if (!size) continue;
        const opt = document.createElement("option");
        opt.value = sizeId;
        opt.textContent = `${sizeText(size, print.orientation)} — ${formatAud(retailPriceAud(size.costFramedAud, config))}`;
        select.appendChild(opt);
    }
    sizeRow.append(sizeLabel, select);

    // Colour swatches
    const colourRow = document.createElement("div");
    colourRow.className = "control-row";
    const colourLabel = document.createElement("label");
    colourLabel.textContent = "Frame";
    const swatches = document.createElement("div");
    swatches.className = "swatches";
    for (const colour of frames.colours) {
        const btn = document.createElement("button");
        btn.type = "button";
        btn.className = "swatch";
        btn.style.background = colour.swatch;
        btn.title = colour.label;
        btn.setAttribute("aria-label", `${colour.label} frame`);
        btn.setAttribute("aria-pressed", String(colour.id === state.colourId));
        btn.addEventListener("click", () => {
            state.colourId = colour.id;
            for (const b of swatches.children) b.setAttribute("aria-pressed", "false");
            btn.setAttribute("aria-pressed", "true");
            frameEl.style.setProperty("--frame-colour", colour.swatch);
        });
        swatches.appendChild(btn);
    }
    colourRow.append(colourLabel, swatches);
    frameEl.style.setProperty("--frame-colour", frames.colours[0].swatch);

    // Matte toggle — the preview's white border is the matte
    const matteRow = document.createElement("div");
    matteRow.className = "control-row";
    const matteLabel = document.createElement("label");
    matteLabel.textContent = "Matte";
    const mattes = document.createElement("div");
    mattes.className = "toggle-group";
    for (const matte of frames.mattes ?? []) {
        const btn = document.createElement("button");
        btn.type = "button";
        btn.className = "toggle";
        btn.textContent = matte.label;
        btn.setAttribute("aria-pressed", String(matte.id === state.matteId));
        btn.addEventListener("click", () => {
            state.matteId = matte.id;
            for (const b of mattes.children) b.setAttribute("aria-pressed", "false");
            btn.setAttribute("aria-pressed", "true");
            inner.classList.toggle("no-matte", matte.id === "no-matte");
        });
        mattes.appendChild(btn);
    }
    matteRow.append(matteLabel, mattes);

    // Price + buy
    const buyRow = document.createElement("div");
    buyRow.className = "buy-row";
    const priceEl = document.createElement("p");
    priceEl.className = "price";
    const buy = document.createElement("button");
    buy.className = "buy";
    buy.textContent = "Buy framed print";
    buy.disabled = !stripeReady;

    function updatePrice() {
        state.sizeId = select.value;
        const size = sizesById[state.sizeId];
        priceEl.innerHTML = "";
        priceEl.append(formatAud(retailPriceAud(size.costFramedAud, config)));
        const small = document.createElement("small");
        small.textContent = "AUD, delivery included";
        priceEl.appendChild(small);
    }
    select.addEventListener("change", updatePrice);
    updatePrice();

    buy.addEventListener("click", async () => {
        const linkInfo = stripeCfg?.products?.[print.slug]?.sizes?.[state.sizeId];

        // Preferred: serverless checkout (passes the chosen colour automatically).
        if (config.checkoutEndpoint && linkInfo?.priceId) {
            buy.disabled = true;
            buy.textContent = "Loading…";
            try {
                const res = await fetch(config.checkoutEndpoint, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ priceId: linkInfo.priceId, colour: state.colourId, matte: state.matteId }),
                });
                const data = await res.json();
                if (!data.url) throw new Error(data.error || "No checkout URL");
                window.location.href = data.url;
                return;
            } catch (err) {
                console.error(err);
                buy.textContent = "Buy framed print";
                buy.disabled = false;
            }
        }

        // Fallback: Stripe Payment Link (colour confirmed via dropdown at checkout).
        if (linkInfo?.paymentLink) {
            window.location.href = linkInfo.paymentLink;
        }
    });

    buyRow.append(priceEl, buy);

    const controls = document.createElement("div");
    controls.className = "controls";
    controls.append(sizeRow, colourRow, ...(mattes.children.length ? [matteRow] : []), buyRow);

    if (print.description) {
        const desc = document.createElement("p");
        desc.className = "desc";
        desc.textContent = print.description;
        card.append(frameEl, h2, desc, controls);
    } else {
        card.append(frameEl, h2, controls);
    }
    return card;
}
